repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
    - id: black
      additional_dependencies: ['toml']

- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: debug-statements
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-json
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  - id: forbid-new-submodules
  - id: no-commit-to-branch
  - id: flake8
    args: ['--exclude=docs/*,*migrations*', '--ignore=E501,W503,E203']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: ['--check-only', '--diff']
    additional_dependencies: ['toml']

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.0
  hooks:
    - id: python-check-mock-methods

