# Generated by Django 2.2.5 on 2019-10-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("calls", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BillRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="price",
                    ),
                ),
                (
                    "end_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_end_record",
                        to="calls.EndRecord",
                    ),
                ),
                (
                    "start_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_start_record",
                        to="calls.StartRecord",
                    ),
                ),
            ],
            options={"verbose_name": "bill", "verbose_name_plural": "bills"},
        )
    ]
